### ISSUE TITLE
Failed to build with Boost 1.77.0

### ISSUE THREAD

**Issue by yurybura** [ig-or/qwtw#2]
I'm working for update Boost for VCPKG (PR https://github.com/microsoft/vcpkg/pull/19556).
I've detected a problem to build `qwtw` library on x64-windows:
[failure logs for x64-windows.zip](https://github.com/ig-or/qwtw/files/7111586/failure.logs.for.x64-windows.zip)
Could you help?

**Comment by ig-or** [comment]
Sorry I didn't looked here for some time..  Will try to look into this

**Comment by JackBoosY** [comment]
Any progress?

**Comment by ig-or** [comment]
Or, sorry,  looks like I moved qwtw to C++20.  For me it looks like the C version is not what is expected..
```
:\buildtrees\qwtw\src\a3c4e419e6-2b585e179b.clean\qwtw\qwtest2.cpp(155): error C2039: 'chrono_literals': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\fstream(26): note: see declaration of 'std'
D:\buildtrees\qwtw\src\a3c4e419e6-2b585e179b.clean\qwtw\qwtest2.cpp(155): error C2871: 'chrono_literals': a namespace with this name does not exist
D:\buildtrees\qwtw\src\a3c4e419e6-2b585e179b.clean\qwtw\qwtest2.cpp(156): error C2039: 'this_thread': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\fstream(26): note: see declaration of 'std'
D:\buildtrees\qwtw\src\a3c4e419e6-2b585e179b.clean\qwtw\qwtest2.cpp(156): error C3083: 'this_thread': the symbol to the left of a '::' must be a type
D:\buildtrees\qwtw\src\a3c4e419e6-2b585e179b.clean\qwtw\qwtest2.cpp(156): error C2039: 'sleep_for': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\fstream(26): note: see declaration of 'std'

```

**Comment by JackBoosY** [comment]
our CI passed this item(VS2022) but I can repro the same issue locally (VS2017).

**Comment by ig-or** [comment]
yes, it looks like VS2022 is using C++20, and VS2017 is previous version..       Will try to repro this locally, maybe there will be some solution
